name = "catforge"
compatibility_date = "2025-04-01"
pages_build_output_dir = "dist"

[build]
command = "npm run build"

[[d1_databases]]
binding = "DB"
database_name = "catforgedb"
database_id = "2a4729ed-8769-492e-a0ac-9105395ee3d9"
